[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "HATasmota"
version = "0.10.1"
description = "Python module to help parse and construct Tasmota MQTT messages."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
authors = []
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "aiohttp>=3.11.12",
    "voluptuous>=0.12.0",
]

[project.urls]
Homepage = "https://github.com/emontnemery/hatasmota"

[dependency-groups]
dev = [
    "black==26.1.0",
    "flake8==7.3.0",
    "flake8-pyproject==1.2.3",
    "isort==8.0.0",
    "mypy==1.19.1",
    "pydantic==2.12.5",
    "pylint==4.0.5",
]

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
include = ["hatasmota*"]

[tool.black]
line-length = 88

[tool.flake8]
# To work with Black
max-line-length = 88
# E501: line too long
# W503: Line break occurred before a binary operator
# E203: Whitespace before ':'
# D202 No blank lines allowed after function docstring
ignore = [
    "E203",
    "E501",
    "W503",
    "D202",
]

[tool.isort]
profile = "black"
combine_as_imports = true
force_sort_within_sections = true

[tool.mypy]
python_version = "3.13"
plugins = ["pydantic.mypy"]
show_error_codes = true
local_partial_types = true
strict_equality = true
no_implicit_optional = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true
enable_error_code = ["ignore-without-code", "redundant-self", "truthy-iterable"]
disable_error_code = ["annotation-unchecked"]
extra_checks = false
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_decorators = true
disallow_untyped_defs = true
warn_return_any = true
warn_unreachable = true
# no_implicit_reexport = true
# disallow_any_generics = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.pylint.main]
load-plugins = [
    "pylint.extensions.code_style",
    "pylint.extensions.typing",
]

[tool.pylint.basic]
good-names = ["id", "i", "j", "k", "x", "ex", "Run", "_", "fp", "T", "ev", "bit"]

[tool.pylint."messages control"]
# Reasons disabled:
# format - handled by black
disable = [
    "consider-using-namedtuple-or-dataclass",
    "duplicate-code",
    "format",
    "too-few-public-methods",
    "too-many-arguments",
    "too-many-branches",
    "too-many-instance-attributes",
    "too-many-locals",
    "too-many-positional-arguments",
    "too-many-return-statements",
    "too-many-statements",
]

[tool.pylint.reports]
score = false

[tool.pylint.format]
expected-line-ending-format = "LF"
