# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.13
        uses: actions/setup-python@v1
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt
      - name: Lint with flake8
        run: |
          flake8 hatasmota
      - name: Lint with pylint
        run: |
          pylint hatasmota
      - name: Lint with mypy
        run: |
          mypy hatasmota
      - name: Check formatting with black
        run: |
          black hatasmota --check --diff
      - name: Check imports with isort
        run: |
          isort hatasmota --check --diff --combine-as --force-sort-within-sections --profile black
